import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("games", "routes/games.tsx"),
  route("games/:slug", "routes/game-slug.tsx"),
  route("games/:slug/ranking", "routes/gameRanking.tsx"),
  route("sandbox-games/:slug", "routes/sandboxGamePlay.tsx"),
  route("ranking", "routes/ranking.tsx"),
  route("profile", "routes/profile.tsx"),
  route("settings", "routes/settings.tsx"),
  route("users/:id", "routes/userProfile.tsx"),
  route("admin", "routes/admin.tsx"),
  route("admin/streamers", "routes/adminStreamers.tsx"),
  route("admin/creators", "routes/legacyAdminStreamerRedirect.tsx"),
  route("admin/games", "routes/adminGames.tsx"),
  route("admin/monitoring", "routes/adminMonitoring.tsx"),
  route("admin/users", "routes/adminUsers.tsx"),
  route("admin/accounts", "routes/adminAccounts.tsx"),
  route("admin/game-creators", "routes/adminGameCreators.tsx"),
  route("admin/sandbox-games", "routes/adminSandboxGames.tsx"),
  route("admin/settings/security", "routes/adminSettingsSecurity.tsx"),
  // Program/Entitlement centers — never Staff Roles, see the same doc.
  route("game-creator", "routes/gameCreatorCenter.tsx"),
  route("discord", "routes/discordHub.tsx"),
  route("discord/setup", "routes/discordSetup.tsx"),
  route("discord/guide", "routes/discordGuide.tsx"),
  route("discord/link", "routes/discordLink.tsx"),
  route("discord/servers", "routes/discordServers.tsx"),
  route("discord/servers/:slug", "routes/discordServerSlug.tsx"),
  route("discord/servers/:slug/manage", "routes/discordServerManage.tsx"),
  route("wiki", "routes/wiki.tsx"),
  route("wiki/getting-started", "routes/wikiGettingStarted.tsx"),
  route("wiki/discord", "routes/wikiDiscord.tsx"),
  route("wiki/discord/install", "routes/wikiDiscordInstall.tsx"),
  route("wiki/discord/account-link", "routes/wikiDiscordAccountLink.tsx"),
  route("wiki/discord/server-registration", "routes/wikiDiscordServerRegistration.tsx"),
  route("wiki/discord/commands", "routes/wikiDiscordCommands.tsx"),
  route("wiki/discord/xp", "routes/wikiDiscordXp.tsx"),
  route("wiki/discord/troubleshooting", "routes/wikiDiscordTroubleshooting.tsx"),
  route("wiki/account", "routes/wikiAccount.tsx"),
  route("wiki/account/merge", "routes/wikiAccountMerge.tsx"),
  route("wiki/games", "routes/wikiGames.tsx"),
  route("wiki/games/development", "routes/wikiGamesDevelopment.tsx"),
  route("wiki/games/ranking", "routes/wikiGamesRanking.tsx"),
  route("wiki/games/xp", "routes/wikiGamesXp.tsx"),
  route("wiki/streamer", "routes/wikiStreamer.tsx"),
  route("wiki/streamer/verification", "routes/wikiStreamerVerification.tsx"),
  route("wiki/streamer/featured", "routes/wikiStreamerFeatured.tsx"),
  route("wiki/creator", "routes/legacyWikiStreamerRedirect.tsx"),
  route("wiki/creator/verification", "routes/legacyWikiStreamerVerificationRedirect.tsx"),
  route("wiki/creator/featured", "routes/legacyWikiStreamerFeaturedRedirect.tsx"),
  route("wiki/support", "routes/wikiSupport.tsx"),
  route("contact", "routes/contact.tsx"),
  route("terms", "routes/terms.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("changelog", "routes/changelog.tsx"),
] satisfies RouteConfig;
